The source code for this project could be found [here](https://github.com/Xianzhiwang1/ml-0451-final-proj). 



# Rough skeleton code harvested from the penguin blog post for easy reference

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from matplotlib import pyplot as plt
import numpy as np
from final_project_code import FinalProject 

In [3]:
import pandas as pd

train_url = "https://raw.githubusercontent.com/middlebury-csci-0451/CSCI-0451/main/data/palmer-penguins/train.csv"
train = pd.read_csv(train_url)

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(train["Species"])
FP = FinalProject()



# X_train, y_train = FP.prepare_data(train)

In [5]:
from itertools import combinations

In [6]:
from matplotlib.patches import Patch


# Predicting whether Russian Factories want to incorporate or not


`$$\mathcal{L}(a, b) = \sum_{i = 1}^n (ax_i + b - y_i)^2$$` 

renders to: 

$$\mathcal{L}(a, b) = \sum_{i = 1}^n (ax_i + b - y_i)^2\;.$$

# get the data in

In [7]:
import pandas as pd

# train_url = "./../Vermont_farm_tables/1850Midd.csv"
# train = pd.read_csv(train_url)

We download the replication data set and put it in the same directory as our project. After we read in the data, we notice that there are $66$ columns, which means potentially we could have around $60$ features for our machine learning model. However, let's start small. Hence, we begin our analysis using a subset of the columns. Also, since in the original data set, there's only a small percentage of factories that are incorporated, which is because of historical reasons in Late Imperial Russia during 1894 to 1908. For the purpose of this machine learning project, we artificially select a subset of the whole data set so that we have equal number of factories owned by incorporated firms and not incorporated firms alike.

In [8]:
# Rvss = pd.io.stata.read_stata("./../Rvssian/AG_Corp_RuscorpMasterFile_Cleaned.dta")
# Rvss.to_csv("RvssianCorpMasterFileCleaned.csv")

In [9]:
# Rvss_data = pd.io.stata.read_stata("./AG_Corp_Prod_Database.dta")
# Rvss_data.to_csv("AG_Corp_Prod_DataBase.csv")

In [10]:
Rvss = pd.read_csv("./AG_Corp_Prod_DataBase.csv")

/tmp/ipykernel_28232/139095848.py:1: DtypeWarning: Columns (3,13) have mixed types. Specify dtype option on import or set low_memory=False.
  Rvss = pd.read_csv("./AG_Corp_Prod_DataBase.csv")


In [11]:
Rvss.head()

Unnamed: 0     id  Form  PSZ PSZ1900  FoundingYear  Province   
0           0   4156     0  NaN     NaN        1860.0        30  \
1           1  52010     0  NaN     NaN           NaN        51   
2           2  30937     0  NaN     NaN           NaN        41   
3           3  39923     0  NaN     NaN           NaN         3   
4           4   3296     0  NaN     NaN        1882.0        11   

              Region             Industry  OntheSide  ...  Animal  Wool   
0  CentralIndustrial                Paper        0.0  ...     0.0   0.0  \
1      Previslitskii              Foods A        NaN  ...     0.0   0.0   
2   CentralBlacksoil              Foods A        NaN  ...     0.0   0.0   
3           Caucasus  Metals and Machines        NaN  ...     0.0   0.0   
4       Northwestern            Chemicals        0.0  ...     0.0   0.0   

   Cotton MixedMaterials Wood  Paper  MetalsandMachines  Foods  Chemical   
0     0.0            0.0  0.0    0.0                0.0    0.0       0.0  \
1     0.0            0.0  0.0    0.0                0.0    1.0       0.0   
2     0.0            0.0  0.0    0.0                0.0    1.0       0.0   
3     0.0            0.0  0.0    0.0                1.0    0.0       0.0   
4     0.0            0.0  0.0    0.0                0.0    0.0       0.0   

   Mineral  
0      0.0  
1      0.0  
2      0.0  
3      0.0  
4      0.0  

[5 rows x 66 columns]

In [12]:
Rvss.columns

Index(['Unnamed: 0', 'id', 'Form', 'PSZ', 'PSZ1900', 'FoundingYear',
       'Province', 'Region', 'Industry', 'OntheSide', 'Age', 'TaxedActivity',
       'YEAR', 'PSZLastYear', 'PSZ1908', 'SubindustryCode', 'STCAP', 'Revenue',
       'TotalWorkers', 'TotalPower', 'GrandTotalWorkers', 'RevperWorker',
       'PowerperWorker', 'RevperGrandWorker', 'PowerperGrandWorker',
       'logRevperWorker', 'logPowerperWorker', 'logRevperGrandWorker',
       'logPowerperGrandWorker', 'logRev', 'logWorkers', 'logPower',
       'RegIndGroup', 'RegIndYearGroup', 'ProvIndGroup', 'ProvIndYearGroup',
       'IndYearGroup', 'IndustryFactor', 'ProvinceFactor', 'YearFactor',
       'AKTS', 'PAI', 'factory_id', 'FormNextYear', 'FormNextNextYear',
       'FactoryisCorpin1894', 'FormNextYearin1894', 'FactoryisCorpin1900',
       'FormNextYearin1900', 'FactoryisCorpin1908', 'NEWDEV', 'SHARES',
       'STPRICE', 'BONDS', 'Silk', 'Flax', 'Animal', 'Wool', 'Cotton',
       'MixedMaterials', 'Wood', 'Paper', 'Metalsa

In [13]:
df = Rvss[['id', 'Form', 'FoundingYear',
       'Province', 'Region', 'Industry', 'OntheSide', 'Age', 'TaxedActivity',
       'YEAR', 'PSZLastYear', 'PSZ1908', 'SubindustryCode', 'STCAP', 'Revenue',
       'TotalWorkers', 'TotalPower', 'GrandTotalWorkers', 'RevperWorker',
       'PowerperWorker', 'RevperGrandWorker', 'PowerperGrandWorker',
       'logRevperWorker', 'logPowerperWorker', 'logRevperGrandWorker',
       'logPowerperGrandWorker', 'logRev', 'logWorkers', 'logPower',
       'RegIndGroup', 'RegIndYearGroup', 'ProvIndGroup', 'ProvIndYearGroup',
       'IndYearGroup', 'IndustryFactor', 'ProvinceFactor', 'YearFactor',
       'AKTS', 'PAI', 'factory_id', 'FormNextYear', 'FormNextNextYear',
       'FactoryisCorpin1894', 'FormNextYearin1894', 'FactoryisCorpin1900',
       'FormNextYearin1900', 'FactoryisCorpin1908', 'NEWDEV', 'SHARES',
       'STPRICE', 'BONDS', 'Silk', 'Flax', 'Animal', 'Wool', 'Cotton',
       'MixedMaterials', 'Wood', 'Paper', 'MetalsandMachines', 'Foods',
       'Chemical', 'Mineral']]

In [14]:
df_inc = df.loc[df['Form'] == 1]

In [15]:
df_not_inc = df.loc[df['Form'] == 0]

In [16]:
print(f"df incorporated have {df_inc.shape[0]} many rows")

df incorporated have 2393 many rows


In [17]:
df_not_inc = df_not_inc.sample(n=2393, replace=False)

In [18]:
print(f"df not incorporated have {df_not_inc.shape[0]} many rows")
frames = [df_inc, df_not_inc]
result = pd.concat(frames)

df not incorporated have 2393 many rows


In [19]:
result['Form'].mean()

0.5

In [20]:
compression_opts = dict(method='zip', archive_name='artificially_balanced_Rvssian_Factory.csv')
result.to_csv('artificially_balanced_Rvssian_Factory.zip', index = False, compression=compression_opts)

In [21]:
result = result.sample(frac=1).reset_index(drop=True)

In [22]:
result.head(10)

id  Form  FoundingYear  Province             Region   
0   1761     0        1855.0        14            Eastern  \
1  15972     0        1879.0        38      Previslitskii   
2  18187     1           NaN        50          Prebaltic   
3  37990     0           NaN        38      Previslitskii   
4     37     1        1871.0        61  CentralIndustrial   
5  25136     1           NaN        35   CentralBlacksoil   
6  17880     1           NaN        30  CentralIndustrial   
7  27039     1           NaN         3           Caucasus   
8  40924     1           NaN        30  CentralIndustrial   
9  25102     0           NaN        32           Northern   

              Industry  OntheSide    Age  TaxedActivity    YEAR  ... Animal   
0               Animal        0.0   40.0            0.0  1894.0  ...    0.0  \
1  Metals and Machines        0.0   16.0            0.0  1894.0  ...    0.0   
2               Cotton        NaN   41.0            NaN  1900.0  ...    0.0   
3               Cotton        NaN    NaN            NaN  1908.0  ...    0.0   
4               Cotton        0.0   24.0            0.0  1894.0  ...    0.0   
5     Mineral Products        NaN  115.0            NaN  1900.0  ...    0.0   
6               Cotton        NaN   34.0            NaN  1900.0  ...    0.0   
7            Chemicals        NaN   16.0            NaN  1900.0  ...    0.0   
8  Metals and Machines        NaN    NaN            NaN  1908.0  ...    0.0   
9     Mineral Products        NaN   19.0            NaN  1900.0  ...    0.0   

  Wool  Cotton  MixedMaterials  Wood  Paper  MetalsandMachines  Foods   
0  0.0     0.0             0.0   0.0    0.0                0.0    0.0  \
1  0.0     0.0             0.0   0.0    0.0                0.0    0.0   
2  0.0     1.0             0.0   0.0    0.0                0.0    0.0   
3  0.0     1.0             0.0   0.0    0.0                0.0    0.0   
4  0.0     0.0             0.0   0.0    0.0                0.0    0.0   
5  0.0     0.0             0.0   0.0    0.0                0.0    0.0   
6  0.0     1.0             0.0   0.0    0.0                0.0    0.0   
7  0.0     0.0             0.0   0.0    0.0                0.0    0.0   
8  0.0     0.0             0.0   0.0    0.0                1.0    0.0   
9  0.0     0.0             0.0   0.0    0.0                0.0    0.0   

   Chemical  Mineral  
0       0.0      0.0  
1       0.0      0.0  
2       0.0      0.0  
3       0.0      0.0  
4       0.0      0.0  
5       0.0      1.0  
6       0.0      0.0  
7       1.0      0.0  
8       0.0      0.0  
9       0.0      1.0  

[10 rows x 63 columns]

In [23]:
FP = FinalProject()
train, validate, test = FP.split_data(result)

In [24]:
df_train, X_train, y_train = FP.prepare_data(train)
df_validate, X_validate, y_validate= FP.prepare_data(validate)
df_test, X_test, y_test = FP.prepare_data(test)

### The Prediction Question:
Can we predict which factory belongs to a incorporated company in Late Imerial Russia, during year 1894 and year 1908, by looking at other variables that are in the data? 

### Data Inspection
Since previously we have artificially selected a subset of our entire Russian factory data set so that we have equal number of factories belonging to incorporated firms and not incorporated firms, we expect that our label has roughly $50 \%$ of $1$'s and $50 \%$ % of $0$'s.

In [25]:
y_train.mean()

0.49703935910832464

In [26]:
df_train.groupby(['Industry'])[['Form']].aggregate([np.mean, len]).round(3)

Form     
                      mean  len
Industry                       
Animal               0.258  178
Chemicals            0.702  205
Cotton               0.787  356
Flax                 0.616   86
Foods A              0.247  453
Metals and Machines  0.604  485
Mineral Products     0.428  271
Mixed Materials      0.507   73
Paper                0.535  226
Silk                 0.250   56
Wood                 0.422  275
Wool                 0.459  207

Hence, it seems that Food industry in Late Imperial Russia had a low incorporation rate, which is around $28.3 \%$. On the other hand, the Cotton industry had a relatively high incorporation rate, around $81.4 \%$.

In [27]:
df_train.groupby(['Industry'])[['TotalPower']].aggregate([np.mean, len]).round(3)

TotalPower     
                          mean  len
Industry                           
Animal                  37.310  178
Chemicals              240.731  205
Cotton                1210.561  356
Flax                   593.383   86
Foods A                 62.312  453
Metals and Machines    253.363  485
Mineral Products       121.442  271
Mixed Materials         97.164   73
Paper                  213.945  226
Silk                    22.500   56
Wood                    63.580  275
Wool                   205.213  207

We see that Cotton industry has the highest mean total power, and Silk industry has the lowest mean total power. We might predict that industry with a higher need for capital might choose to incorporate. 
### Running some regressions 
We start with the standard procedure in Econometrics, which is running regressions. We first perform some regression analysis that is close in spirit to the published paper where this replication data set is coming from, and   

In [65]:

from sklearn.linear_model import LogisticRegression

# this counts as 3 features because the two Clutch Completion 
# columns are transformations of a single original measurement. 
# you should find a way to automatically select some better columns
# as suggested in the code block above
cols = ["id", "FoundingYear", "Industry", "TotalWorkers", "TotalPower", "GrandTotalWorkers", "logWorkers", "Mineral"]
cols = ['id', 'FoundingYear',
       'Province', 'Region', 'OntheSide', 'Age', 'TaxedActivity',
       'YEAR', 'SubindustryCode', 'STCAP', 'Revenue',
       'TotalWorkers', 'TotalPower', 'GrandTotalWorkers', 'RevperWorker',
       'PowerperWorker', 'RevperGrandWorker', 'PowerperGrandWorker',
       'logRevperWorker', 'logPowerperWorker', 'logRevperGrandWorker',
       'logPowerperGrandWorker', 'logRev', 'logWorkers', 'logPower',
       'RegIndGroup', 'RegIndYearGroup', 'ProvIndGroup', 'ProvIndYearGroup',
       'IndYearGroup', 'IndustryFactor', 'ProvinceFactor', 'YearFactor',
       'AKTS', 'PAI', 'factory_id', 'FormNextYear', 'FormNextNextYear',
       'FactoryisCorpin1894', 'FormNextYearin1894', 'FactoryisCorpin1900',
       'FormNextYearin1900', 'FactoryisCorpin1908', 'NEWDEV', 'SHARES',
       'STPRICE', 'BONDS', 'Silk', 'Flax', 'Animal', 'Wool', 'Cotton',
       'MixedMaterials', 'Wood', 'Paper', 'MetalsandMachines', 'Foods',
       'Chemical', 'Mineral']
cols = ['id', 'FoundingYear', 'Province', 'OntheSide', 'Age', 'TaxedActivity',
       'YEAR', 'PSZLastYear', 'PSZ1908', 'SubindustryCode', 'STCAP', 'Revenue',
       'TotalWorkers', 'TotalPower', 'GrandTotalWorkers', 'RevperWorker',
       'PowerperWorker', 'RevperGrandWorker', 'PowerperGrandWorker',
       'logRevperWorker', 'logPowerperWorker', 'logRevperGrandWorker',
       'logPowerperGrandWorker', 'logRev', 'logWorkers', 'logPower',
       'RegIndGroup', 'RegIndYearGroup', 'ProvIndGroup', 'ProvIndYearGroup',
       'IndYearGroup', 'IndustryFactor', 'ProvinceFactor', 'YearFactor',
       'AKTS', 'PAI', 'factory_id', 'FormNextYear', 'FormNextNextYear',
       'FactoryisCorpin1894', 'FormNextYearin1894', 'FactoryisCorpin1900',
       'FormNextYearin1900', 'FactoryisCorpin1908', 'NEWDEV', 'SHARES',
       'STPRICE', 'BONDS', 'Silk', 'Flax', 'Animal', 'Wool', 'Cotton',
       'MixedMaterials', 'Wood', 'Paper', 'MetalsandMachines', 'Foods',
       'Chemical', 'Mineral']
# X_train = X_train.dropna()
# X_train = X_train.drop(["Industry"], axis=1)
# X_train = X_train.drop(["Region"], axis=1)
# X_train.drop(["FoundingYear", "OntheSide", "TaxedActivity", "PSZLastYear", "PSZ1908"], axis=1)
# X_train = X_train.fillna(0)
# y_train.reset_index(drop=True)
cols = ["TotalWorkers", "TotalPower", "Revenue", "Age", 
        "Silk", "Flax", "Animal", "Wool", "Cotton", "MixedMaterials", 
        "Wood", "Paper", "MetalsandMachines", "Foods", "Chemical", "Mineral"]

LR = LogisticRegression()
LR.fit(X_train[cols], y_train)
LR.score(X_train[cols], y_train)

0.6464646464646465

In [66]:
X_train[cols]

TotalWorkers  TotalPower   Revenue   Age  Silk  Flax  Animal  Wool   
2897          50.0         0.0   31400.0  12.0   0.0   0.0     0.0   0.0  \
4435          22.0        60.0       0.0   0.0   0.0   0.0     0.0   0.0   
2309          52.0         0.0   89900.0   0.0   0.0   0.0     0.0   0.0   
763           99.0         0.0  207800.0  32.0   0.0   0.0     0.0   0.0   
4397          22.0         0.0   18300.0   0.0   0.0   0.0     0.0   0.0   
...            ...         ...       ...   ...   ...   ...     ...   ...   
575           36.0         0.0    6677.0   1.0   0.0   0.0     0.0   0.0   
3790           7.0         0.0   18000.0  19.0   0.0   0.0     0.0   0.0   
3980         131.0         0.0   83206.0   0.0   1.0   0.0     0.0   0.0   
1706          16.0         2.0   21778.0   0.0   0.0   0.0     0.0   0.0   
3471         317.0       250.0  451032.0   0.0   0.0   0.0     0.0   0.0   

      Cotton  MixedMaterials  Wood  Paper  MetalsandMachines  Foods  Chemical   
2897     0.0             0.0   0.0    0.0                1.0    0.0       0.0  \
4435     0.0             0.0   0.0    0.0                0.0    1.0       0.0   
2309     0.0             0.0   0.0    0.0                0.0    0.0       0.0   
763      0.0             1.0   0.0    0.0                0.0    0.0       0.0   
4397     0.0             0.0   0.0    0.0                1.0    0.0       0.0   
...      ...             ...   ...    ...                ...    ...       ...   
575      0.0             0.0   0.0    0.0                0.0    0.0       0.0   
3790     0.0             0.0   0.0    0.0                1.0    0.0       0.0   
3980     0.0             0.0   0.0    0.0                0.0    0.0       0.0   
1706     0.0             0.0   0.0    1.0                0.0    0.0       0.0   
3471     0.0             1.0   0.0    0.0                0.0    0.0       0.0   

      Mineral  
2897      0.0  
4435      0.0  
2309      0.0  
763       0.0  
4397      0.0  
...       ...  
575       0.0  
3790      0.0  
3980      0.0  
1706      0.0  
3471      0.0  

[2871 rows x 16 columns]

In [68]:
pd.DataFrame({
    "column": X_train[cols].columns,
    "coefficient": LR.coef_.ravel()
})

column  coefficient
0        TotalWorkers     0.002543
1          TotalPower    -0.000432
2             Revenue     0.000001
3                 Age    -0.018715
4                Silk    -0.000046
5                Flax    -0.000030
6              Animal    -0.000121
7                Wool    -0.000127
8              Cotton    -0.000055
9      MixedMaterials    -0.000012
10               Wood    -0.000116
11              Paper    -0.000052
12  MetalsandMachines     0.000021
13              Foods    -0.000339
14           Chemical     0.000071
15            Mineral    -0.000141

In [69]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline

In [70]:
def poly_LR(deg):
    return Pipeline([("poly", PolynomialFeatures(degree=deg)),
                     ("LR", LogisticRegression(penalty="none", max_iter=int(1e3)))])

In [91]:
plr = poly_LR(1)
plr.fit(X_train[cols], y_train)
plr.score(X_train[cols], y_train)

/home/xianzhiwang/miniforge3/envs/ml-0451/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:1173: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(


0.6509926854754441

In [85]:
from sklearn.model_selection import cross_val_score
cv_scores = cross_val_score(plr, X_train[cols], y_train, cv=5)
cv_scores

/home/xianzhiwang/miniforge3/envs/ml-0451/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:1173: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/home/xianzhiwang/miniforge3/envs/ml-0451/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:1173: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/home/xianzhiwang/miniforge3/envs/ml-0451/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:1173: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/home/xianzhiwang/miniforge3/envs/ml-0451/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:1173: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past beha

array([0.62782609, 0.5       , 0.64634146, 0.50696864, 0.6445993 ])

In [86]:
cv_scores.mean()

0.5851470989244054

Hence, this is telling us that for the features we selected, polynomial logistic regression has roughly the same predictive power as simply guessing whether a factory is belonging to a corporation or not. Degree zero corresponds to the baseline model, and degree 1 corresponds to simple logistic regression without a polynomial feature map.

In [ ]:
for deg in range(3):
    plr = poly_LR(deg = deg)
    cv_scores = cross_val_score(plr, X_train[cols], y_train, cv=5)
    mean_score = cv_scores.mean()  
    print(f"Polynomial degree = {deg}, score = {mean_score.round(3)}")

In [87]:
X_test = X_test.fillna(0)
plr.score(X_test[cols], y_test).round(4)

0.6378

In [96]:
from sklearn.metrics import confusion_matrix
y_predict = plr.predict(X_test[cols])
confusion_matrix(y_test, y_predict)

array([[201, 304],
       [ 43, 410]])

In [97]:
confusion_matrix(y_test, y_predict, normalize = "true")

array([[0.3980198 , 0.6019802 ],
       [0.09492274, 0.90507726]])

In [98]:
X_test["PowerperWorker"].mean()

0.6348312793559499

In [100]:
ix = X_test["PowerperWorker"] > 0.63483127
print("Factories with more power per worker than average")
print(f"The percentage our prediction is correct: {(y_test[ix] == y_predict[ix]).mean()}")
confusion_matrix(y_test[ix], y_predict[ix], normalize="true")

Factories with more power per worker
The percentage our prediction is correct: 0.618421052631579


array([[0.23584906, 0.76415094],
       [0.04918033, 0.95081967]])

In [102]:

ix = X_test["PowerperWorker"] < 0.63483127
print("Factories with less power per worker than average")
print(f"The percentage our prediction matches the actual label: {(y_test[ix] == y_predict[ix]).mean()}")
confusion_matrix(y_test[ix], y_predict[ix], normalize="true")

Factories with less power per worker than average
The percentage our prediction matches the actual label: 0.6438356164383562


array([[0.44110276, 0.55889724],
       [0.11178248, 0.88821752]])

In [105]:
y_test[X_test["PowerperWorker"] > 0.63483127]

827     0
984     0
4758    0
4420    1
3908    1
       ..
130     0
2919    1
3171    0
4426    1
860     0
Name: Form, Length: 228, dtype: int64

In [104]:
y_test

126     0
3950    0
2935    1
3204    0
1347    0
       ..
4426    1
466     1
3092    0
3772    0
860     0
Name: Form, Length: 958, dtype: int64